# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\coordinatessetupwidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoordinatesSetupWidget(object):
    def setupUi(self, CoordinatesSetupWidget):
        CoordinatesSetupWidget.setObjectName("CoordinatesSetupWidget")
        CoordinatesSetupWidget.resize(372, 771)
        self.gridLayout = QtWidgets.QGridLayout(CoordinatesSetupWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(CoordinatesSetupWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 360, 759))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.chkHoles = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkHoles.setChecked(True)
        self.chkHoles.setObjectName("chkHoles")
        self.verticalLayout_2.addWidget(self.chkHoles)
        self.chkMillings = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkMillings.setChecked(True)
        self.chkMillings.setObjectName("chkMillings")
        self.verticalLayout_2.addWidget(self.chkMillings)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.chkBoardMirrored = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkBoardMirrored.setChecked(True)
        self.chkBoardMirrored.setObjectName("chkBoardMirrored")
        self.verticalLayout_2.addWidget(self.chkBoardMirrored)
        self.chkBoardOutlines = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkBoardOutlines.setChecked(True)
        self.chkBoardOutlines.setObjectName("chkBoardOutlines")
        self.verticalLayout_2.addWidget(self.chkBoardOutlines)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 0, 1, 1, 1)
        self.txtBoardSizeX = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtBoardSizeX.setMinimumSize(QtCore.QSize(130, 0))
        self.txtBoardSizeX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtBoardSizeX.setFont(font)
        self.txtBoardSizeX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBoardSizeX.setReadOnly(False)
        self.txtBoardSizeX.setObjectName("txtBoardSizeX")
        self.gridLayout_2.addWidget(self.txtBoardSizeX, 1, 0, 1, 1)
        self.txtBoardSizeY = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtBoardSizeY.setMinimumSize(QtCore.QSize(130, 0))
        self.txtBoardSizeY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtBoardSizeY.setFont(font)
        self.txtBoardSizeY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBoardSizeY.setReadOnly(False)
        self.txtBoardSizeY.setObjectName("txtBoardSizeY")
        self.gridLayout_2.addWidget(self.txtBoardSizeY, 1, 1, 1, 1)
        self.btnApplyBoardSize = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnApplyBoardSize.setObjectName("btnApplyBoardSize")
        self.gridLayout_2.addWidget(self.btnApplyBoardSize, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtNewParkZ = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewParkZ.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewParkZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewParkZ.setFont(font)
        self.txtNewParkZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewParkZ.setReadOnly(False)
        self.txtNewParkZ.setObjectName("txtNewParkZ")
        self.gridLayout_4.addWidget(self.txtNewParkZ, 4, 2, 1, 1)
        self.txtNewParkX = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewParkX.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewParkX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewParkX.setFont(font)
        self.txtNewParkX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewParkX.setReadOnly(False)
        self.txtNewParkX.setObjectName("txtNewParkX")
        self.gridLayout_4.addWidget(self.txtNewParkX, 1, 2, 1, 1)
        self.txtParkX = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtParkX.setMinimumSize(QtCore.QSize(130, 0))
        self.txtParkX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtParkX.setFont(font)
        self.txtParkX.setStyleSheet("background-color: #EEEEEE;")
        self.txtParkX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtParkX.setReadOnly(True)
        self.txtParkX.setObjectName("txtParkX")
        self.gridLayout_4.addWidget(self.txtParkX, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.txtNewParkY = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewParkY.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewParkY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewParkY.setFont(font)
        self.txtNewParkY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewParkY.setReadOnly(False)
        self.txtNewParkY.setObjectName("txtNewParkY")
        self.gridLayout_4.addWidget(self.txtNewParkY, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.txtParkZ = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtParkZ.setMinimumSize(QtCore.QSize(130, 0))
        self.txtParkZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtParkZ.setFont(font)
        self.txtParkZ.setStyleSheet("background-color: #EEEEEE;")
        self.txtParkZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtParkZ.setReadOnly(True)
        self.txtParkZ.setObjectName("txtParkZ")
        self.gridLayout_4.addWidget(self.txtParkZ, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtParkY = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtParkY.setMinimumSize(QtCore.QSize(130, 0))
        self.txtParkY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtParkY.setFont(font)
        self.txtParkY.setStyleSheet("background-color: #EEEEEE;")
        self.txtParkY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtParkY.setReadOnly(True)
        self.txtParkY.setObjectName("txtParkY")
        self.gridLayout_4.addWidget(self.txtParkY, 2, 1, 1, 1)
        self.btnGotoParkPosition = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnGotoParkPosition.setObjectName("btnGotoParkPosition")
        self.gridLayout_4.addWidget(self.btnGotoParkPosition, 5, 1, 1, 1)
        self.btnApplyParkPos = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnApplyParkPos.setObjectName("btnApplyParkPos")
        self.gridLayout_4.addWidget(self.btnApplyParkPos, 6, 2, 1, 1)
        self.btnNewParkPosSetCurrent = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnNewParkPosSetCurrent.setObjectName("btnNewParkPosSetCurrent")
        self.gridLayout_4.addWidget(self.btnNewParkPosSetCurrent, 5, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.txtNewBoardY = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewBoardY.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewBoardY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewBoardY.setFont(font)
        self.txtNewBoardY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewBoardY.setReadOnly(False)
        self.txtNewBoardY.setObjectName("txtNewBoardY")
        self.gridLayout_5.addWidget(self.txtNewBoardY, 2, 2, 1, 1)
        self.txtNewBoardZ = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewBoardZ.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewBoardZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewBoardZ.setFont(font)
        self.txtNewBoardZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewBoardZ.setReadOnly(False)
        self.txtNewBoardZ.setObjectName("txtNewBoardZ")
        self.gridLayout_5.addWidget(self.txtNewBoardZ, 4, 2, 1, 1)
        self.txtNewBoardX = FocusLineEdit(self.scrollAreaWidgetContents)
        self.txtNewBoardX.setMinimumSize(QtCore.QSize(130, 0))
        self.txtNewBoardX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtNewBoardX.setFont(font)
        self.txtNewBoardX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNewBoardX.setReadOnly(False)
        self.txtNewBoardX.setObjectName("txtNewBoardX")
        self.gridLayout_5.addWidget(self.txtNewBoardX, 1, 2, 1, 1)
        self.txtBoardX = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtBoardX.setMinimumSize(QtCore.QSize(130, 0))
        self.txtBoardX.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtBoardX.setFont(font)
        self.txtBoardX.setStyleSheet("background-color: #EEEEEE;")
        self.txtBoardX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBoardX.setReadOnly(True)
        self.txtBoardX.setObjectName("txtBoardX")
        self.gridLayout_5.addWidget(self.txtBoardX, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 4, 0, 1, 1)
        self.txtBoardY = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtBoardY.setMinimumSize(QtCore.QSize(130, 0))
        self.txtBoardY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtBoardY.setFont(font)
        self.txtBoardY.setStyleSheet("background-color: #EEEEEE;")
        self.txtBoardY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBoardY.setReadOnly(True)
        self.txtBoardY.setObjectName("txtBoardY")
        self.gridLayout_5.addWidget(self.txtBoardY, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.btnNewBoardSetCurrent = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnNewBoardSetCurrent.setObjectName("btnNewBoardSetCurrent")
        self.gridLayout_5.addWidget(self.btnNewBoardSetCurrent, 5, 2, 1, 1)
        self.txtBoardZ = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtBoardZ.setMinimumSize(QtCore.QSize(130, 0))
        self.txtBoardZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.txtBoardZ.setFont(font)
        self.txtBoardZ.setStyleSheet("background-color: #EEEEEE;")
        self.txtBoardZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBoardZ.setReadOnly(True)
        self.txtBoardZ.setObjectName("txtBoardZ")
        self.gridLayout_5.addWidget(self.txtBoardZ, 4, 1, 1, 1)
        self.btnApplyBoardOrigin = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnApplyBoardOrigin.setObjectName("btnApplyBoardOrigin")
        self.gridLayout_5.addWidget(self.btnApplyBoardOrigin, 6, 2, 1, 1)
        self.btnGotoBoardOrigin = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnGotoBoardOrigin.setObjectName("btnGotoBoardOrigin")
        self.gridLayout_5.addWidget(self.btnGotoBoardOrigin, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(CoordinatesSetupWidget)
        QtCore.QMetaObject.connectSlotsByName(CoordinatesSetupWidget)

    def retranslateUi(self, CoordinatesSetupWidget):
        _translate = QtCore.QCoreApplication.translate
        CoordinatesSetupWidget.setWindowTitle(_translate("CoordinatesSetupWidget", "Form"))
        self.label_8.setText(_translate("CoordinatesSetupWidget", "Tasks"))
        self.chkHoles.setText(_translate("CoordinatesSetupWidget", "Holes"))
        self.chkMillings.setText(_translate("CoordinatesSetupWidget", "Millings"))
        self.label_7.setText(_translate("CoordinatesSetupWidget", "Board Settings"))
        self.chkBoardMirrored.setText(_translate("CoordinatesSetupWidget", "Mirrored"))
        self.chkBoardOutlines.setText(_translate("CoordinatesSetupWidget", "Show Outlines"))
        self.label_29.setText(_translate("CoordinatesSetupWidget", "Size X"))
        self.label_30.setText(_translate("CoordinatesSetupWidget", "Size Y"))
        self.txtBoardSizeX.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtBoardSizeY.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.btnApplyBoardSize.setText(_translate("CoordinatesSetupWidget", "Apply"))
        self.label.setText(_translate("CoordinatesSetupWidget", "Park Position"))
        self.txtNewParkZ.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtNewParkX.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtParkX.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.label_2.setText(_translate("CoordinatesSetupWidget", "Coordinates"))
        self.label_10.setText(_translate("CoordinatesSetupWidget", "Y"))
        self.txtNewParkY.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.label_3.setText(_translate("CoordinatesSetupWidget", "New Coordinates"))
        self.label_11.setText(_translate("CoordinatesSetupWidget", "Z"))
        self.txtParkZ.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.label_12.setText(_translate("CoordinatesSetupWidget", "X"))
        self.txtParkY.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.btnGotoParkPosition.setText(_translate("CoordinatesSetupWidget", "Go"))
        self.btnApplyParkPos.setText(_translate("CoordinatesSetupWidget", "Apply"))
        self.btnNewParkPosSetCurrent.setText(_translate("CoordinatesSetupWidget", "Set to current"))
        self.label_6.setText(_translate("CoordinatesSetupWidget", "Default Board Origin"))
        self.label_4.setText(_translate("CoordinatesSetupWidget", "Coordinates"))
        self.txtNewBoardY.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtNewBoardZ.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtNewBoardX.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.txtBoardX.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.label_14.setText(_translate("CoordinatesSetupWidget", "Z"))
        self.txtBoardY.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.label_15.setText(_translate("CoordinatesSetupWidget", "X"))
        self.label_5.setText(_translate("CoordinatesSetupWidget", "New Coordinates"))
        self.label_13.setText(_translate("CoordinatesSetupWidget", "Y"))
        self.btnNewBoardSetCurrent.setText(_translate("CoordinatesSetupWidget", "Set to current"))
        self.txtBoardZ.setText(_translate("CoordinatesSetupWidget", "000.000"))
        self.btnApplyBoardOrigin.setText(_translate("CoordinatesSetupWidget", "Apply"))
        self.btnGotoBoardOrigin.setText(_translate("CoordinatesSetupWidget", "Go"))

from ui.FocusLineEdit import FocusLineEdit
