# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 653)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.splitterRight = QtWidgets.QSplitter(self.centralwidget)
        self.splitterRight.setOrientation(QtCore.Qt.Horizontal)
        self.splitterRight.setChildrenCollapsible(False)
        self.splitterRight.setObjectName("splitterRight")
        self.splitterBottom = QtWidgets.QSplitter(self.splitterRight)
        self.splitterBottom.setOrientation(QtCore.Qt.Vertical)
        self.splitterBottom.setChildrenCollapsible(False)
        self.splitterBottom.setObjectName("splitterBottom")
        self.workpieceViewer = WorkpieceWidget(self.splitterBottom)
        self.workpieceViewer.setMinimumSize(QtCore.QSize(0, 500))
        self.workpieceViewer.setObjectName("workpieceViewer")
        self.lstLog = QtWidgets.QListWidget(self.splitterBottom)
        self.lstLog.setObjectName("lstLog")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitterRight)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabControl = QtWidgets.QWidget()
        self.tabControl.setObjectName("tabControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabControl)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wdgControl = ControlWidget(self.tabControl)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.wdgControl.setFont(font)
        self.wdgControl.setObjectName("wdgControl")
        self.gridLayout_2.addWidget(self.wdgControl, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabControl, "")
        self.tabCoordSetup = QtWidgets.QWidget()
        self.tabCoordSetup.setObjectName("tabCoordSetup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabCoordSetup)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wdgCoordinateSetup = CoordinatesSetupWidget(self.tabCoordSetup)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.wdgCoordinateSetup.setFont(font)
        self.wdgCoordinateSetup.setObjectName("wdgCoordinateSetup")
        self.gridLayout_3.addWidget(self.wdgCoordinateSetup, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCoordSetup, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnStartCycle = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStartCycle.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartCycle.setFont(font)
        self.btnStartCycle.setObjectName("btnStartCycle")
        self.verticalLayout.addWidget(self.btnStartCycle)
        self.gridLayout.addWidget(self.splitterRight, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mnuAbout = QtWidgets.QAction(MainWindow)
        self.mnuAbout.setObjectName("mnuAbout")
        self.mnuSettings = QtWidgets.QAction(MainWindow)
        self.mnuSettings.setObjectName("mnuSettings")
        self.mnuOpenEagleBrd = QtWidgets.QAction(MainWindow)
        self.mnuOpenEagleBrd.setObjectName("mnuOpenEagleBrd")
        self.mnuQuit = QtWidgets.QAction(MainWindow)
        self.mnuQuit.setObjectName("mnuQuit")
        self.mnuAboutQt = QtWidgets.QAction(MainWindow)
        self.mnuAboutQt.setObjectName("mnuAboutQt")
        self.mnuInitMachine = QtWidgets.QAction(MainWindow)
        self.mnuInitMachine.setObjectName("mnuInitMachine")
        self.mnuApplyMachineParams = QtWidgets.QAction(MainWindow)
        self.mnuApplyMachineParams.setObjectName("mnuApplyMachineParams")
        self.mnuCloseMachine = QtWidgets.QAction(MainWindow)
        self.mnuCloseMachine.setObjectName("mnuCloseMachine")
        self.actionRun_homing_cycle = QtWidgets.QAction(MainWindow)
        self.actionRun_homing_cycle.setObjectName("actionRun_homing_cycle")
        self.mnuDocumentation = QtWidgets.QAction(MainWindow)
        self.mnuDocumentation.setObjectName("mnuDocumentation")
        self.menufile.addAction(self.mnuOpenEagleBrd)
        self.menufile.addSeparator()
        self.menufile.addAction(self.mnuQuit)
        self.menuTools.addAction(self.mnuInitMachine)
        self.menuTools.addAction(self.mnuApplyMachineParams)
        self.menuTools.addAction(self.actionRun_homing_cycle)
        self.menuTools.addAction(self.mnuCloseMachine)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.mnuSettings)
        self.menuHelp.addAction(self.mnuDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.mnuAbout)
        self.menuHelp.addAction(self.mnuAboutQt)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ESCMillPCB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabControl), _translate("MainWindow", "Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoordSetup), _translate("MainWindow", "Setup"))
        self.btnStartCycle.setText(_translate("MainWindow", "Start Cycle"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.mnuAbout.setText(_translate("MainWindow", "About..."))
        self.mnuSettings.setText(_translate("MainWindow", "Settings..."))
        self.mnuOpenEagleBrd.setText(_translate("MainWindow", "Open Eagle Board..."))
        self.mnuQuit.setText(_translate("MainWindow", "Quit"))
        self.mnuAboutQt.setText(_translate("MainWindow", "About Qt..."))
        self.mnuInitMachine.setText(_translate("MainWindow", "(Re-)Initialize machine"))
        self.mnuApplyMachineParams.setText(_translate("MainWindow", "(Re-)Apply machine settings"))
        self.mnuCloseMachine.setText(_translate("MainWindow", "Close machine connection"))
        self.actionRun_homing_cycle.setText(_translate("MainWindow", "Run homing cycle"))
        self.mnuDocumentation.setText(_translate("MainWindow", "Documentation"))

from ui.ControlWidget import ControlWidget
from ui.CoordinatesSetupWidget import CoordinatesSetupWidget
from ui.WorkpieceWidget import WorkpieceWidget
