# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\settingsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(628, 838)
        SettingsDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSoftwareSettings = QtWidgets.QWidget()
        self.tabSoftwareSettings.setObjectName("tabSoftwareSettings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabSoftwareSettings)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.paramsSoftwareSettings = ParameterTree(self.tabSoftwareSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsSoftwareSettings.sizePolicy().hasHeightForWidth())
        self.paramsSoftwareSettings.setSizePolicy(sizePolicy)
        self.paramsSoftwareSettings.setObjectName("paramsSoftwareSettings")
        self.gridLayout_2.addWidget(self.paramsSoftwareSettings, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tabSoftwareSettings)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.tabSoftwareSettings)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSoftwareSettings, "")
        self.tabBasicMachineSettings = QtWidgets.QWidget()
        self.tabBasicMachineSettings.setObjectName("tabBasicMachineSettings")
        self.gridLayout = QtWidgets.QGridLayout(self.tabBasicMachineSettings)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.paramsMachineBasic = ParameterTree(self.tabBasicMachineSettings)
        self.paramsMachineBasic.setObjectName("paramsMachineBasic")
        self.gridLayout.addWidget(self.paramsMachineBasic, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabBasicMachineSettings, "")
        self.tabAdvancedMachineSettings = QtWidgets.QWidget()
        self.tabAdvancedMachineSettings.setObjectName("tabAdvancedMachineSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabAdvancedMachineSettings)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tabAdvancedMachineSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboMachine = QtWidgets.QComboBox(self.tabAdvancedMachineSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboMachine.sizePolicy().hasHeightForWidth())
        self.comboMachine.setSizePolicy(sizePolicy)
        self.comboMachine.setObjectName("comboMachine")
        self.horizontalLayout_2.addWidget(self.comboMachine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.tabAdvancedMachineSettings)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.paramsMachineCom = ParameterTree(self.tabAdvancedMachineSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsMachineCom.sizePolicy().hasHeightForWidth())
        self.paramsMachineCom.setSizePolicy(sizePolicy)
        self.paramsMachineCom.setMinimumSize(QtCore.QSize(0, 200))
        self.paramsMachineCom.setObjectName("paramsMachineCom")
        self.verticalLayout_2.addWidget(self.paramsMachineCom)
        self.label_3 = QtWidgets.QLabel(self.tabAdvancedMachineSettings)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.paramsMachineAdvanced = ParameterTree(self.tabAdvancedMachineSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsMachineAdvanced.sizePolicy().hasHeightForWidth())
        self.paramsMachineAdvanced.setSizePolicy(sizePolicy)
        self.paramsMachineAdvanced.setObjectName("paramsMachineAdvanced")
        self.verticalLayout_2.addWidget(self.paramsMachineAdvanced)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnReadMachineParams = QtWidgets.QPushButton(self.tabAdvancedMachineSettings)
        self.btnReadMachineParams.setObjectName("btnReadMachineParams")
        self.horizontalLayout.addWidget(self.btnReadMachineParams)
        self.btnApplyMachineParams = QtWidgets.QPushButton(self.tabAdvancedMachineSettings)
        self.btnApplyMachineParams.setObjectName("btnApplyMachineParams")
        self.horizontalLayout.addWidget(self.btnApplyMachineParams)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabAdvancedMachineSettings, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setAccessibleName("")
        self.buttonBox.setAccessibleDescription("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.lineEdit.setText(_translate("SettingsDialog", "%LOCALAPPDATA%\\ESCMillPCB"))
        self.label_4.setText(_translate("SettingsDialog", "Application data directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSoftwareSettings), _translate("SettingsDialog", "Software Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBasicMachineSettings), _translate("SettingsDialog", "Basic Machine Settings"))
        self.label.setText(_translate("SettingsDialog", "Machine"))
        self.label_2.setText(_translate("SettingsDialog", "Communication Settings"))
        self.label_3.setText(_translate("SettingsDialog", "Machine parameters"))
        self.btnReadMachineParams.setText(_translate("SettingsDialog", "Read from device"))
        self.btnApplyMachineParams.setText(_translate("SettingsDialog", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvancedMachineSettings), _translate("SettingsDialog", "Advanced Machine Settings"))

from pyqtgraph.parametertree.ParameterTree import ParameterTree
