# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\TinyGCycleControl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TinyGCycleControl(object):
    def setupUi(self, TinyGCycleControl):
        TinyGCycleControl.setObjectName("TinyGCycleControl")
        TinyGCycleControl.resize(520, 400)
        TinyGCycleControl.setModal(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TinyGCycleControl)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(TinyGCycleControl)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lstCommandBuffer = QtWidgets.QListWidget(TinyGCycleControl)
        self.lstCommandBuffer.setObjectName("lstCommandBuffer")
        self.verticalLayout_3.addWidget(self.lstCommandBuffer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lblLinebuffer = QtWidgets.QLabel(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLinebuffer.sizePolicy().hasHeightForWidth())
        self.lblLinebuffer.setSizePolicy(sizePolicy)
        self.lblLinebuffer.setObjectName("lblLinebuffer")
        self.verticalLayout.addWidget(self.lblLinebuffer)
        self.prgLinebuffer = QtWidgets.QProgressBar(TinyGCycleControl)
        self.prgLinebuffer.setProperty("value", 24)
        self.prgLinebuffer.setTextVisible(False)
        self.prgLinebuffer.setObjectName("prgLinebuffer")
        self.verticalLayout.addWidget(self.prgLinebuffer)
        self.lblPlannerQueue = QtWidgets.QLabel(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlannerQueue.sizePolicy().hasHeightForWidth())
        self.lblPlannerQueue.setSizePolicy(sizePolicy)
        self.lblPlannerQueue.setObjectName("lblPlannerQueue")
        self.verticalLayout.addWidget(self.lblPlannerQueue)
        self.prgPlannerQueue = QtWidgets.QProgressBar(TinyGCycleControl)
        self.prgPlannerQueue.setProperty("value", 24)
        self.prgPlannerQueue.setTextVisible(False)
        self.prgPlannerQueue.setObjectName("prgPlannerQueue")
        self.verticalLayout.addWidget(self.prgPlannerQueue)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lblOutputBuffer = QtWidgets.QLabel(TinyGCycleControl)
        self.lblOutputBuffer.setObjectName("lblOutputBuffer")
        self.verticalLayout.addWidget(self.lblOutputBuffer)
        self.prgOutputBuffer = QtWidgets.QProgressBar(TinyGCycleControl)
        self.prgOutputBuffer.setProperty("value", 24)
        self.prgOutputBuffer.setTextVisible(False)
        self.prgOutputBuffer.setObjectName("prgOutputBuffer")
        self.verticalLayout.addWidget(self.prgOutputBuffer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFeedhold = QtWidgets.QPushButton(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFeedhold.sizePolicy().hasHeightForWidth())
        self.btnFeedhold.setSizePolicy(sizePolicy)
        self.btnFeedhold.setMinimumSize(QtCore.QSize(0, 30))
        self.btnFeedhold.setCheckable(True)
        self.btnFeedhold.setObjectName("btnFeedhold")
        self.horizontalLayout.addWidget(self.btnFeedhold)
        self.btnStop = QtWidgets.QPushButton(TinyGCycleControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btnStop.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TinyGCycleControl)
        QtCore.QMetaObject.connectSlotsByName(TinyGCycleControl)

    def retranslateUi(self, TinyGCycleControl):
        _translate = QtCore.QCoreApplication.translate
        TinyGCycleControl.setWindowTitle(_translate("TinyGCycleControl", "TinyG Cycle Control"))
        self.label.setText(_translate("TinyGCycleControl", "Command buffer"))
        self.label_2.setText(_translate("TinyGCycleControl", "Hardware buffer"))
        self.lblLinebuffer.setText(_translate("TinyGCycleControl", "Linebuffer: 4 / 8"))
        self.lblPlannerQueue.setText(_translate("TinyGCycleControl", "Planner Queue: 4 / 32"))
        self.label_3.setText(_translate("TinyGCycleControl", "Progress"))
        self.lblOutputBuffer.setText(_translate("TinyGCycleControl", "Command 12 / 1245"))
        self.btnFeedhold.setText(_translate("TinyGCycleControl", "Feedhold"))
        self.btnStop.setText(_translate("TinyGCycleControl", "STOP"))

